import unittest
import sys
import os
currentFolder = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.join(currentFolder, '../../util'))
sys.path.insert(0, os.path.join(currentFolder, '../../moveNearReplace'))
sys.path.insert(0, os.path.join(currentFolder, '..'))
import color
import assertMy
import coffee_compile_model
import os
import filer2 as filer


class Test(unittest.TestCase):
	def test_testName(self):
		color.blue("test here baby")
		expectedJsFile=os.path.join(currentFolder, 'poligon/poligon.js')
		os.remove(expectedJsFile)
		filename=os.path.join(currentFolder, 'poligon/poligon.coffee')
		coffee_compile_model.coffeeCompile(filename)
		js=filer.read(expectedJsFile).strip()
		expectedJs="""// Generated by CoffeeScript 1.8.0
var hello;

hello = function() {
  return console.log("world");
};

""".strip()
		assertMy.equals(js, expectedJs)

if __name__ == '__main__':
	unittest.main()