import unittest
import sys
sys.path.insert(0, '/Users/maks/Library/Application Support/Sublime Text 3/Packages/util')
sys.path.insert(0, '/Users/maks/Library/Application Support/Sublime Text 3/Packages/coffee')
import color
import assertMy
import coffee_compile_model
import os
sys.path.insert(0, '/Users/maks/Library/Application Support/Sublime Text 3/Packages/moveNearReplace')
import filer2 as filer


class Test(unittest.TestCase):
	def test_testName(self):
		color.blue("test here baby")
		expectedJsFile="/Users/maks/Library/Application Support/Sublime Text 3/Packages/coffee/test/poligon/poligon.js"
		os.remove(expectedJsFile)
		filename="/Users/maks/Library/Application Support/Sublime Text 3/Packages/coffee/test/poligon/poligon.coffee"
		coffee_compile_model.coffeeCompile(filename)
		js=filer.read(expectedJsFile).strip()
		expectedJs="""// Generated by CoffeeScript 1.8.0
var hello;

hello = function() {
  return console.log("world");
};

""".strip()
		assertMy.equals(js, expectedJs)

if __name__ == '__main__':
	unittest.main()